---
title: "01 Approaches and data generation"
output: html_notebook
---

# Objectives

1) Identify, extract, transform, generate, etc. data as needed to estimate fundraising revenue
2) Compare various projection models, methods, and rules of thumb
3) Create a reproducible workflow to forecast fundraising outcomes

# Initial thoughts

### Data

At a minimum, giving is a function of wealth, affinity, and timing. Anything impacting either of these is a potential predictor.

$$ G = f(w,a,t) $$

Frequently, $w$ and $a$ are 

### Outliers

Anecdotally, many organizations model annual gifts separately from major or principal gifts. This makes a lot of sense given that annual gifts and major/principal gifts are generated by very different processes, and annual gifts tend to have a much larger sample size and smaller variance.

Earlier this year, I [ran a simulation](https://htmlpreview.github.io/?https://github.com/phively/demos/blob/master/Synthetic%20campaign%20pipeline%20simulation.nb.html) examining how large proposals (outliers) blow up forecasts. "Large" is a function of gift size, pipeline size, and close probability, but given the industry standard $p \approx 1/3$ close rate, treat with caution any single proposal near or above $1/4$ of the total pipeline value.

### Approaches

I've seen two common approaches. First, model revenue as a time series with the previous year's results (and maybe including a couple assumed-to-be-correlated series, e.g. S&P 500 or VIX). This is frequently used with annual giving. Second, model revenue as a function of gift officer activity, such as the proposal pipeline, expected visit dates, etc. This is more commonly used to forecast yearly or campaign progress.

