---
title: "03 Data file output"
output:
  html_notebook:
    toc: TRUE
    toc_float:
      collapsed: FALSE
---

# Goal

Create a set of modeling-ready, time-sliced data files with featuretoolsR.

# Setup

```{r setup, message = FALSE, warning = FALSE}
library(tidyverse)
library(lubridate)
library(wranglR)
library(readxl)
library(foreach)
library(reticulate)
library(nanotime)
library(featuretoolsR)

source(file = 'code/featuretools helper functions.R')
```

# Load and check data

```{r, warning = FALSE}
data_dt <- '2020-04-08'
source(file = 'code/data xlsx import.R')
source(file = 'code/data cleanup.R')
source(file = 'code/data validation.R')
```

# Set up Python session

```{python}
import featuretools as ft
```

# Create entity sets

```{r}
fy18 <- entityset_create(
  entityset_name = 'fy18'
  , datalist = catracks
  , cutoff_dt = ymd('20180831')
  , master_entity = 'households'
  , master_idx = 'HOUSEHOLD_ID'
  , debug = TRUE
)
```

View results.

```{r}
fy18
```

Add interesting values.

```{r}
fy18$add_interesting_values(max_values = 6L)
```

# Full run

```{r, cache = TRUE}
# Full run (slow)
# dfs_output_fy18 <- fy18 %>%
#   dfs(
#    target_entity = 'households'
#    , agg_primitives = c('count', 'sum', 'std', 'mean', 'max', 'min', 'median', 'first', 'last', 'percent_true')
#    , trans_primitives = c('cum_sum', 'cum_max', 'month', 'year', 'subtract_numeric', 'divide_numeric', 'time_since_previous')
#    , max_depth = 2
#    , verbose = TRUE
# )
# 
# save('dfs_output_fy18', file = 'data/output/dfs_output_fy18.Rdata')
```

